### ISSUE TITLE
Error connecting to your code-server instance

### ISSUE THREAD

**Issue by drmrbrewer** [cdr/deploy-code-server#72]
I am trying to deploy code-server on a [Hetzner cloud server](https://www.hetzner.com/cloud)... I expected this to be the same process as for [digitalocean](https://github.com/cdr/deploy-code-server/blob/main/guides/digitalocean.md) because after all it's just an Ubuntu server and there is also the option with Hetzner to specify User Data (i.e. the install script).

But when I navigate to the IP of the new server, I get the initial github link/authentication screen, and after agreeing to this, I then get:

    Error connecting to your code-server instance
    Ensure code-server is running and was properly started with the --link command line flag.

![image](https://user-images.githubusercontent.com/9009792/142760002-5890fa76-720d-4266-ae09-61363f56bd51.png)

**Comment by MrTechieCode** [comment]
You are not alone.
Also fails on Digital Ocean

**Comment by bpmct** [comment]
Hi - sorry for the delayed response.

We are probably going to be deprecating the `--link` functionality because it fails under some circumstances. The feature will remain available, but will not be recommended. 

The following troubleshooting steps should help:
- 1) https://github.com/bpmct/coder-cloud-redirect-server/blob/master/README.md#troubleshooting
- 2) https://github.com/cdr/code-server/issues/2734
